### ISSUE TITLE
node_asan npm broken on OS X

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#191]
Seeing this for unknown reasons:

```
module.js:327
    throw err;
    ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/travis/build/mapbox/node-cpp-skel/mason_packages/osx-x86_64/node_asan/4.4.5/bin/npm:19:11
    at Object.<anonymous> (/Users/travis/build/mapbox/node-cpp-skel/mason_packages/osx-x86_64/node_asan/4.4.5/bin/npm:76:3)
```

**Comment by mikemorris** [comment]
Huh, I didn't really notice this when I used it, i guess because I just used my regular version of Node.js/npm to install everything, then called the asan `node` binary directly to run.

**Comment by springmeyer** [comment]
no longer actionable. Building node with asan is not longer needed - recent versions of clang++/compiler-rt allow using LD_PRELOAD to push the sanitizer shared libraries into the process such that you can now instrument a node C++ addon and effectively test it with an uninstrumented node.
